import { Component, Inject } from '@angular/core';
import { MAT_DIALOG_DATA, MatDialogRef } from '@angular/material/dialog';
import { CommentService } from 'src/app/services/comments/comment.service';
import { Recipe } from '../models/recipe';
import { Comment } from '../models/comment';
import { User } from '../models/user';

@Component({
  selector: 'app-reply-dialog',
  templateUrl: './reply-dialog.component.html',
  styleUrls: ['./reply-dialog.component.sass'],
})
export class ReplyDialogComponent {
  replyContent: string = '';

  constructor(
    public dialogRef: MatDialogRef<ReplyDialogComponent>,
    private commentService: CommentService,

    @Inject(MAT_DIALOG_DATA)
    public data: { commentId: string; recipe: Recipe; user: User }
  ) {}

  onSendReply() {
    const commentId = this.data.commentId;
    const recipe = this.data.recipe;
    const user = this.data.user;
    const replyContent = this.replyContent;

    const reply: Comment = {
      id: '', // The ID will be generated by Firestore
      content: replyContent,
      user: user, // Set the user who sent the reply
      recipe: recipe, // Set the recipe under which the reply is added
      timestamp: new Date(),
      replies: [],
      upvotes: [],
      downvotes: [],
    };

    this.commentService
      .addReply(commentId, reply)
      .then(() => {
        this.dialogRef.close(true); // Pass any result if needed
      })
      .catch((error: any) => {
        console.error('Failed to add reply:', error);
        // Handle the error if necessary
      });
  }

  onCancel() {
    this.dialogRef.close(); // Close the dialog without result
  }
}
